# Cloud Run Service Configuration for TenaAI Backend
# This file can be used with: gcloud run services replace cloudrun-deploy.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tenaai-backend
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling settings
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Request timeout
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/cpu-throttling: "false"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: tenaai-backend-sa@YOUR_PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: gcr.io/YOUR_PROJECT_ID/tenaai-backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
            - name: CORS_ORIGIN
              value: "https://your-firebase-project.web.app"
            # Secret references - these should be created in Secret Manager
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: latest
            - name: FIREBASE_SERVICE_ACCOUNT_BASE64
              valueFrom:
                secretKeyRef:
                  name: firebase-service-account
                  key: latest
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
